### ISSUE TITLE
Hiding podcasts + experimental features flags now blocks all home screen sections

### ISSUE THREAD

**Issue by RWCoding58** [Nuzair46/SpotX-Mac#52]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

Singapore

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for macOS (Intel)
1.2.4.912.g949d5fd0
- macOS: macOS Ventura 13.2
- Shell: zsh
```

### 📝 Description

1. Run the Spot-X installation script with the -h and -e flags (`bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh) -eh`)
2. Open Spotify
3. Everything besides the "Good evening" section is missing

### 🖥️ Terminal Input/Output

************************
SpotX-Mac by @SpotX-CLI
************************

Spotify version: 1.2.4.912
SpotX-Mac version: 1.2.3.1115-1

Creating xpui backup...
Extracting xpui...
Applying SpotX patches...
Removing ad-related content...
Removing premium-only features...
Unlocking Spotify Connect...
Adding experimental features...
Removing logging...
Enabling new home screen UI...
Hiding non-music items on home screen...
Rebuilding xpui...
SpotX finished patching!

### 📸 Screenshots

<img width="1439" alt="Screenshot 2023-02-03 at 21 30 46" src="https://user-images.githubusercontent.com/87898490/216615624-c896097b-8423-4340-9a51-c9e2626a340e.png">
(pardon my music taste)

**Comment by Nuzair46** [comment]
Disabled this feature. For now, not adding any experimental features. Just pure adblocking.
