### ISSUE TITLE
UI Spacing & Bugs (-o flag used) 

### ISSUE THREAD

**Issue by jimmysofat6864** [Nuzair46/SpotX-Mac#59]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for macOS (Intel) 1.2.11.916.geb595a67
- macOS: 12.6.3
- Shell: zsh
```

### 📝 Description

UI Has some spacing bugs and glitches mainly at the top where it says sponsored. 

### 🖥️ Terminal Input/Output

bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh) -o -f

************************
SpotX-Mac by @SpotX-CLI
************************

Spotify version: 1.2.11.916
SpotX-Mac version: 1.2.3.1115-1

Creating xpui backup...
Extracting xpui...
Applying SpotX patches...
Removing ad-related content...
Removing premium-only features...
Unlocking Spotify Connect...
Removing logging...
Skipping new home UI patch...
Rebuilding xpui...
SpotX finished patching!

### 📸 Screenshots

<img width="1126" alt="Screen Shot 2023-05-20 at 11 19 36 AM" src="https://github.com/SpotX-CLI/SpotX-Mac/assets/69532417/dc3a8009-5190-41b7-91fa-8b9a2a5bde16">
<img width="314" alt="Screen Shot 2023-05-20 at 11 14 58 AM" src="https://github.com/SpotX-CLI/SpotX-Mac/assets/69532417/63a21194-00b4-40a3-8e5d-2bee20bec936">
<img width="1460" alt="Screen Shot 2023-05-20 at 11 14 51 AM" src="https://github.com/SpotX-CLI/SpotX-Mac/assets/69532417/bbd60b8c-5c13-4e6d-b6db-260832d9545f">

**Comment by jimmysofat6864** [comment]
Using the fork linked here fixed my issue. 

https://github.com/jetfir3/SpotX-Bash/tree/main

**Comment by Nuzair46** [comment]
removed this flag
