### ISSUE TITLE
Error: Flag not supported

### ISSUE THREAD

**Issue by electriquo** [Nuzair46/SpotX-Mac#68]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

NA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
NA
```

### 📝 Description

The documentation is not up to date. The (un)instllation block holds invalid argument. For instance, `-ce`

https://github.com/Nuzair46/SpotX-Mac/blob/ce2a7a69f36046c03dbf6645c578bc9fefc90110/readme.md?plain=1#L53-L66

### 🖥️ Terminal Input/Output

```shell
Error: Flag not supported.
```

**Comment by Nuzair46** [comment]
I think you used the unsupported flag in the installation command -ce. i will remove it from the readme. Incase you used some other flag, please let me know.
